/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ConnectionsRouteImport } from './routes/connections'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as MessagesUserIdRouteImport } from './routes/messages.$userId'
import { Route as BoxIdRouteImport } from './routes/box.$id'
import { Route as AuthenticatedPostRouteImport } from './routes/_authenticated/post'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsRoute = ConnectionsRouteImport.update({
  id: '/connections',
  path: '/connections',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesUserIdRoute = MessagesUserIdRouteImport.update({
  id: '/messages/$userId',
  path: '/messages/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const BoxIdRoute = BoxIdRouteImport.update({
  id: '/box/$id',
  path: '/box/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPostRoute = AuthenticatedPostRouteImport.update({
  id: '/post',
  path: '/post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/connections': typeof ConnectionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/post': typeof AuthenticatedPostRoute
  '/box/$id': typeof BoxIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/connections': typeof ConnectionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/post': typeof AuthenticatedPostRoute
  '/box/$id': typeof BoxIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/browse': typeof BrowseRoute
  '/connections': typeof ConnectionsRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/_authenticated/post': typeof AuthenticatedPostRoute
  '/box/$id': typeof BoxIdRoute
  '/messages/$userId': typeof MessagesUserIdRoute
  '/u/$username': typeof UUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/connections'
    | '/notifications'
    | '/profile'
    | '/post'
    | '/box/$id'
    | '/messages/$userId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/connections'
    | '/notifications'
    | '/profile'
    | '/post'
    | '/box/$id'
    | '/messages/$userId'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/browse'
    | '/connections'
    | '/notifications'
    | '/profile'
    | '/_authenticated/post'
    | '/box/$id'
    | '/messages/$userId'
    | '/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrowseRoute: typeof BrowseRoute
  ConnectionsRoute: typeof ConnectionsRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  BoxIdRoute: typeof BoxIdRoute
  MessagesUserIdRoute: typeof MessagesUserIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections': {
      id: '/connections'
      path: '/connections'
      fullPath: '/connections'
      preLoaderRoute: typeof ConnectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages/$userId': {
      id: '/messages/$userId'
      path: '/messages/$userId'
      fullPath: '/messages/$userId'
      preLoaderRoute: typeof MessagesUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/box/$id': {
      id: '/box/$id'
      path: '/box/$id'
      fullPath: '/box/$id'
      preLoaderRoute: typeof BoxIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/post': {
      id: '/_authenticated/post'
      path: '/post'
      fullPath: '/post'
      preLoaderRoute: typeof AuthenticatedPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPostRoute: typeof AuthenticatedPostRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPostRoute: AuthenticatedPostRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrowseRoute: BrowseRoute,
  ConnectionsRoute: ConnectionsRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  BoxIdRoute: BoxIdRoute,
  MessagesUserIdRoute: MessagesUserIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
